### ISSUE TITLE
Server table & data tests failing (not finding IP address)

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/quimby#76]
This came up when I was working on something else, realized these tests fail even for master branch:

```
  1) Servers index table displays server information
     Failure/Error: expect(body).to have_text('123.45.67.890')
       expected to find text "123.45.67.890" in "Quimby Quimby Repositories Servers server-dev pupgraded"
     # ./spec/features/servers_table_spec.rb:10:in `block (2 levels) in <top (required)>'

  2) ServerPuppetdbData#load_data with valid response creates objects from api response
     Failure/Error: expect(server.ip).to eq '123.45.67.890'

       expected: "123.45.67.890"
            got: nil

       (compared using ==)
     # ./spec/models/server_puppetdb_data_spec.rb:29:in `block (4 levels) in <top (required)>'
```

It just looks like the ip address isn't getting passed in the test object, but happy to try to look at later today if someone else doesn't have time / can't fix in like 2 seconds.

**Comment by cmh2166** [comment]
stubbed out fake responses to the puppetdb api calls, and the tests work. 

not sure why tests should rely on access to an external service (especially when fake responses are given), and that seems problematic. but happy to close this and consider my own ignorance the reason.
